### ISSUE TITLE
How to use go_router_builder 

### ISSUE THREAD

**Issue by q200892907** [JakesMD/flutter_go_router_tabs#2]

**Comment by JakesMD** [comment]
Hi! I need some kind of context or else I can't help you. Are you sure you've posted in the correct repo?

**Comment by alterhuman** [comment]
@JakesMD 
I think they're asking how to use this package alongside go_router_builder as it has different way of adding a shell route. I have the same query.

**Comment by JakesMD** [comment]
> [!Warning]
> This package has been discontinued. Please use go_router's `StatefulShellRoute` instead ([see an example here](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/stateful_shell_route.dart)).

Sadly due to the lack of documentation I was unaware of the `StatefulShellRoute`. Now there is no need for this package any longer.
